{
 "title": "Pomegranate Disease Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Uploads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"Total Uploads\" FROM predictions"
    }
   ]
  },
  {
   "title": "Disease Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) filter (where detected_disease = 'Alternaria') as \"Alternaria\", count(*) filter (where detected_disease = 'Anthracnose') as \"Anthracnose\", count(*) filter (where detected_disease = 'Bacterial_Blight') as \"Bacterial_Blight\", count(*) filter (where detected_disease = 'Cercospora') as \"Cercospora\", count(*) filter (where detected_disease = 'Healthy') as \"Healthy\" FROM predictions"
    }
   ]
  },
  {
   "title": "Recent Predictions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT image_hash, detected_disease, timestamp FROM predictions ORDER BY timestamp DESC LIMIT 20"
    }
   ]
  }
 ]
}